use_frameworks!

platform :ios, '8.0'

target 'YFLaunchedTaskManager_Example' do

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
    pod 'YFLaunchedTaskManager'

end
